// examples/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import SelectableGrid from "@selectable-grid/vue";

const imgRef = ref<HTMLImageElement>();
</script>

<template>
  <div class="image-container">
    <img
      ref="imgRef"
      id="img"
      src="https://avatars.mds.yandex.net/get-mpic/5219318/img_id3258925543469117996.jpeg/orig"
      alt=""
    />
  </div>
  <SelectableGrid
    v-if="imgRef"
    :options="{
      imageContainer: imgRef,
      cellCount: 15,
    }"
  />
</template>

<style scoped>
#img {
  height: 500px;
}
</style>

// examples/react/src/App.tsx
import React, { useRef, useState } from 'react'
import SelectableGrid from '@selectable-grid/react'

const App = () => {
  const imgRef = useRef<HTMLImageElement>()
  const [_, setIsLoad] = useState(false)

  return (
    <div style={{ position: 'relative' }}>
      <img
        ref={imgRef}
        src='spanch-bob.webp'
        alt='Spanch Bob'
        height={500}
        onLoad={() => setIsLoad(true)}
      />
      <SelectableGrid cellCount={20} imageContainer={imgRef.current} />
    </div>
  )
}

export default App
